# Generated by Django 2.2.4 on 2019-08-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clone_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_ip', models.CharField(max_length=100)),
                ('type_status', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('usb', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'devices',
                'managed': True,
            },
        ),
    ]
