# Generated by Django 2.2.4 on 2019-08-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clone_model',
            name='ip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
